### ISSUE TITLE
URL Schema with Headers

### ISSUE THREAD

**Issue by Pytal** [piglovesyou/graphql-let#104]
Currently the validator gives an error that the schema must be a string when you pass it a URL with headers.

The graphql-codegen [schema docs](https://graphql-code-generator.com/docs/getting-started/schema-field#url) support this format:

``` yaml
schema:
  - http://localhost:3000/graphql:
      headers:
        Authorization: YOUR-TOKEN-HERE
```

It'd be great to have support for this in `graphq-let` as well 🙌
