### ISSUE TITLE
Disable generating of Resolver Types

### ISSUE THREAD

**Issue by johnrackles** [piglovesyou/graphql-let#140]
I don't need to generate resolver types, but everytime graphql-let runs I get ons of messages like this in my logs:

`[ graphql-let ] Failed to generate Resolver Types. You have to specify at least one schema (glob) path WITH an extension, such as "**/*.graphqls`

Per the documentation, this happens when you have `@graphql-codegen/typescript-resolvers` installed but this seems to be installed with graphql-let and I wasn't able to uninstall it. Is there another way to disable the Generation of resolver types?

My config:

```yaml
schema: 'http://***.com/graphql'
documents:
  - 'src/**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  reactApolloVersion: 3
  withComponent: false
TSConfigFile: ./tsconfig.graphql-let.json
respectGitIgnore: true
cacheDir: __generated__
```

Thanks!
