### ISSUE TITLE
Environment variables in .graphql-let.yml

### ISSUE THREAD

**Issue by vattenapa** [piglovesyou/graphql-let#144]
(Follow up from #104)

In my setup I have a remote schema from a CMS together with some client only stuff that's in a local schema definition file. To fetch the CMS schema I need to pass a fresh JWT. Iwould like to be able to set the token in an environment variable so that it doesn't need to hard coded, nor have to create an intermediate file that graphql-let can use. Coupled with #104 and #49 this would solve the use case quite nicely.

What I have done in the past using graphql-codegen is configuring it something like this:
```
schema:
  - ${GRAPHQL_ENDPOINT}:
      headers:
        Authorization: Bearer ${ACCESS_TOKEN}
  - lib/type-defs.graphqls
[...]
```
and then passing environment variables which would then be expanded. Does/should this work using graphql-let? Perhaps I'm doing it wrong, but I'm unable to get it to work...

---

Bonus question: I'm using `dotenv-expand` to reference a .env variable within another one, something like this:
```
CMS_BASE_URL="https://foo.baz.bar"
GRAPHQL_ENDPOINT="${CMS_BASE_URL}/graphql"
```
Should/could this be supported too?
