### ISSUE TITLE
Breaking change react hooks

### ISSUE THREAD

**Issue by botond-veress** [piglovesyou/graphql-let#183]
Hey,

First of all thank you for maintaining this lib. I really like it! 👍 

I just upgraded from 0.13.0 to 0.15.3 and react hooks are no longer generated.

This is my config file:
```yaml
schema: ${API}/graphql
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
respectGitIgnore: true
config:
  reactApolloVersion: 3
  maybeValue: T | undefined
  scalars:
    Date: String
    DateTime: String
```

If I switch back to version 0.13.0 everything works as expected. Unfortunately it doesn't support environment variables in the yaml file, so I had to upgrade to a newer version.

**Update**: After a few hours of research I found out that most likely the graphql-codegen defaults were updated in the meantime so I had to explicitly add to the config:
```yaml
config:
  ...
  withComponent: false
  withHOC: false
  withHooks: true
```

Maybe it would worth mentioning in the release logs.
