### ISSUE TITLE
Not compatible with graphql-code-generator's typescript-vue-apollo plugin?

### ISSUE THREAD

**Issue by cdrx** [piglovesyou/graphql-let#215]
Installed packages:
```
    "@graphql-codegen/cli": "^1.17.10",
    "@graphql-codegen/plugin-helpers": "^1.17.9",
    "@graphql-codegen/typescript": "^1.17.10",
    "@graphql-codegen/typescript-operations": "^1.17.8",
    "@graphql-codegen/typescript-vue-apollo": "^2.1.0",
    "graphql-let": "^0.16.2",
```

`.graphql-let.yml` looks like:
```
schema: schema.graphqls
documents: "src/**/*.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-vue-apollo
```

When running `npx graphql-let` I get:

```
$ npx graphql-let 
[ graphql-let ] Running graphql-codegen...
(node:15503) ExperimentalWarning: The fs.promises API is experimental
[ graphql-let ] Plugin "typescript-vue-apollo" validation failed:
            Plugin "vue-apollo" requires extension to be ".ts"!
          Error: Plugin "typescript-vue-apollo" validation failed:
            Plugin "vue-apollo" requires extension to be ".ts"!
          
    at executePlugin (frontend/node_modules/@graphql-codegen/core/index.cjs.js:33:19)
[ graphql-let ] Something went wrongListrError: Something went wrong
    at tasks.then (frontend/node_modules/listr/index.js:102:18)
```

**Plugin "vue-apollo" requires extension to be ".ts"!**

Using `graphql-code-generator` directly does work, using `codegen.yml`:
```
overwrite: true
schema: schema.graphqls
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-vue-apollo
```

I don't understand this stuff well enough to know where to start debugging this, so any help or suggestions would be appreciated.
