### ISSUE TITLE
Is it possible to generate enum to UPPER_CASE?

### ISSUE THREAD

**Issue by saenalcha** [piglovesyou/graphql-let#353]
I have a question.

ex) graphql file
```
enum SomeType {
  ..
  ORDER_ID
  ..
}
```

is generated to
```
export enum SomeType {
  ..
  OrderId = 'ORDER_ID'
  ..
}
```

***But Is it possible to generate it like this?***
```
export enum SomeType {
  ..
  ORDER_ID = 'ORDER_ID'
  ..
}
```

**Comment by piglovesyou** [comment]
Hi @saenalcha. Not sure but why don't you take a look at [namingConvention option](https://graphql-code-generator.com/docs/plugins/typescript)?

**Comment by saenalcha** [comment]
Thank you @piglovesyou ~!
`namingConvention option` goes well.

```
config:
  namingConvention:
    typeNames: pascal-case#pascalCase
    enumValues: upper-case#upperCase
```
