### ISSUE TITLE
Cannot read property 'definitions' of undefined.

### ISSUE THREAD

**Issue by ALITHEALI** [piglovesyou/graphql-let#44]
Hi, in this [new release (v0.6.2)](https://github.com/piglovesyou/graphql-let/releases/tag/v0.6.1), the CLI fails with below error. 

![carbon](https://user-images.githubusercontent.com/44507581/73406891-7d002580-42ef-11ea-9f71-a8198ded1a96.png)

I tried cleaning up the workspace (rm -rf node_modules yarn.lock __generated__ .next) and also to revert back to v0.5.2. I'm not sure about this error but I suspect it might be from `@graphql-codegen/typescript-operations` but it's just an assumption.

**Comment by ALITHEALI** [comment]
Oh I forgot to post my config file, here it is: 

```yaml

generateDir: __generated__
schema: http://localhost:4000
documents: ./graphql/**/*.gql
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo

```

I also tried changing the document format to .graphqls and .graphql but it doesn't seem to be the issue:
```yaml
generateDir: __generated__
schema: http://localhost:4000
documents: ./graphql/**/*.graphqls
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo

```
