### ISSUE TITLE
Query and Mutation always return any instead of a fully typed

### ISSUE THREAD

**Issue by stevenho0811** [piglovesyou/graphql-let#478]
I don't know what mistake I have made. and I stuck this problem for a week still can't figure it out ...

graphql-let.yml:

```yml
  schema: '../common/schema.gql'
  documents: '**/*.graphql'
  plugins:
    - typescript
    - typescript-operations
    - typescript-react-apollo
```

auth.graphql:
<img width="301" alt="Screen Shot 2021-05-10 at 12 21 05 AM" src="https://user-images.githubusercontent.com/4948562/117579493-9f553580-b125-11eb-90fb-9e7dbd6abd55.png">

```
query Viewer {
  viewer {
      id
  }
}
```
Generated auth.graphql.ts:
<img width="449" alt="Screen Shot 2021-05-10 at 12 22 43 AM" src="https://user-images.githubusercontent.com/4948562/117579526-d7f50f00-b125-11eb-92ea-7e4d0bfbac61.png">
<img width="1105" alt="Screen Shot 2021-05-10 at 12 23 09 AM" src="https://user-images.githubusercontent.com/4948562/117579539-e80cee80-b125-11eb-9e3b-d0fea5223f0a.png">
