### ISSUE TITLE
Generate types in place other than `node_modules`

### ISSUE THREAD

**Issue by cloudagon** [piglovesyou/graphql-let#487]
Whenever I make a change to my packages and the `node_modules` folder is updated, I have to regenerate the types. Is there a way I can specify a folder to generate types in, other than `node_modules/graphql-let/__generated__/__types__`?.

**Comment by piglovesyou** [comment]
Hi @cloudagon, I didn't know the behavior. Thanks for letting me know.

 You probably mean `node_modules/@types/graphql-let/__generated__/__types__.d.ts`, generated in the default [`typeInjectEntrypoint`](https://github.com/piglovesyou/graphql-let/blob/a1c63e2f3d14ea6c8aee5c734b435eee55f51534/src/lib/config.ts#L83) directory. Not tested, but setting `typeInjectEntrypoint: typings/graphql-let.d.ts` or something must avoid it.

**Comment by cloudagon** [comment]
It just generates an empty file in the specified location. This aligns with `node_modules/graphql-let/__generated__/index.d.ts`.

**Comment by piglovesyou** [comment]
`dirname(config.typeInjectEntrypoint)` is a directory graphql-let should generate types in, but I have no test case for it. The file having empty content is ok. It only gets to have declarations when needed. I'm happy if you (or anyone):

1. describe what happens when you change `typeInjectEntrypoint` and what problem remains still
1. make a PR of the reproduction test case
2. make a PR to solve it

**Comment by cloudagon** [comment]
When I set the following:
```yml
typeInjectEntrypoint: src/types/graphql-let
```
no types are generated. An empty file called `graphql-let` is generated in `src/types` and the `node_modules/@types/graphql-let` is **not** created.

full config:
```yml
schema: src/graphql/**/*.graphqls
documents: src/graphql/**/*.graphql
typeInjectEntrypoint: src/types/graphql-let
plugins:
  - typescript-operations
  - typescript-react-apollo
config:
  enumValues:
    Language: '@prisma/client#Language'
  enumPrefix: GQL
cacheDir: .cache/graphql-let
```
I'm willing to look into this, but I'm not even sure where to start.
