### ISSUE TITLE
Couldn't find schema.graphqls.d.ts file/s

### ISSUE THREAD

**Issue by three-seagrass** [piglovesyou/graphql-let#630]
In the documentations, it is stated that by running `yarn graphql-let`, files such as `query.graphql.d.ts` and `schema.graphqls.d.ts` will be generated. However, I could not find any `schema.graphqls.d.ts` files. Only `query.graphql.d.ts` files are being generated. Is it because in v0.18.0, all of the types live in `graphql-let/__generated__/__types__`?

My yml file below:

```yml
schema: 'lib/**.graphqls'
documents:
   - '**/*.graphql'
plugins:
   - typescript-operations
   - typescript-react-apollo
cacheDir: .cache
```

Thanks!
