### ISSUE TITLE
No types getting generated

### ISSUE THREAD

**Issue by hendrik244** [piglovesyou/graphql-let#654]
I'm currently trying to generate typesscript types via CLI, but no type files a getting created.

 My queries are stored in .ts files and look like this for example:

<img width="548" alt="image" src="https://github.com/piglovesyou/graphql-let/assets/33331414/ea8b4ba5-b988-4116-884f-f502036a7d12">

My .graphql-let.yml looks like this:

```
schema:
  - https://XXXXXX-dev.myshopify.com/api/2023-01/graphql.json:
      headers:
        X-Shopify-Storefront-Access-Token: XXXXXXXXXXXXX
documents:
  - 'src/lib/shopify/queries/*.ts*'
  - 'src/lib/shopify/mutations/*.ts*'
plugins:
  - typescript-operations
cacheDir: .cache/graphql-let
```

The cache file "__types__.tsx" is getting created.

Following packages are installed:

"graphql-let": "^0.18.6",
"graphql": "^16.8.1",
"@graphql-codegen/cli": "5.0.0",
"@graphql-codegen/typescript": "^4.0.1",
"@graphql-codegen/typescript-operations":

What am I doing wrong?
Thanks in advance
