### ISSUE TITLE
Accept object as "schema" configuration

### ISSUE THREAD

**Issue by v-morlock** [piglovesyou/graphql-let#85]
graphQL codegen supports setting custom headers for schema introspection using an object as the "schema" attribute, e.g.:

```
schema:
  - http://localhost:3000/graphql:
      headers:
        Authorization: YOUR-TOKEN-HERE
```
