### ISSUE TITLE
Cryptic error when contextType not found

### ISSUE THREAD

**Issue by paulbellamy** [piglovesyou/graphql-let#89]
Example config:

```yaml
# Breaks the build
config:
  contextType: './file-which-does-not-exist'

# Other default stuff.. doesn't matter.
generateDir: __generated__
schema: '**/*.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
respectGitIgnore: true
```

Observed error:
```
TypeScript API was not expected as graphql-let developer, it needs to be fixed
```

Expected behaviour:
Not sure, something a bit more descriptive of the underlying problem... It took me a while to debug this.
