### ISSUE TITLE
Allow multiple schema files

### ISSUE THREAD

**Issue by marklawlor** [piglovesyou/graphql-let#97]
Currently the when using Resolver Types it will only work when using a single schema file. It would be nice if it worked with the array and/or glob syntax like graphql-codegen does.

**Comment by marklawlor** [comment]
If a single file is required, is there a change that import syntax as per https://github.com/ardatan/graphql-import could be supported?

**Comment by piglovesyou** [comment]
Hi! Thanks for pointing it out, that's what it changed recently. I'd like to hear your idea, how the import syntax will look if the schema path is a glob?

**Comment by marklawlor** [comment]
I would only recommend using the graphql-import syntax if a glob is not possible due to the inner workings of this project.

I'm trying to migrate a codebase that is currently using graphql-codegen to graphql-let

My previous codegen.yaml file was 

```
schema: "src/lib/graphql/**/*.graphql"
generates:
  src/lib/graphql/schema.d.ts:
  plugins:
    - typescript
    - typescript-operations
    - typescript-resolvers
  config:
    namingConvention: "keep"
    contextType: <path to context>
    scalars:
      Date: "Date"
      Time: "Date"
      DateTime: "Date"
    mappers:
      <type>: <path>
```

My current .graphql-let.yml

```
schema: "src/lib/graphql/schema.graphqls"
documents: "**/*.graphql"
respectGitIgnore: true
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  - typescript-resolvers
config:
  namingConvention: "keep"
  contextType: <path to context>
  scalars:
    Date: "Date"
    Time: "Date"
    DateTime: "Date"
  mappers:
    <type>: <path>
```

I believe the .graphql-let.yml is simply missing an output parameter on where to write the schema to if a glob is used

**Comment by marklawlor** [comment]
Renaming this topic to just "Allow multiple schema files"as there are more use cases to support multiple schemas

I was attempting to follow the [apollo-local-state integration instructions for graphql-code-generator](https://graphql-code-generator.com/docs/integrations/apollo-local-state) which recommend you use two schemas, a frontend and backend schema and combine them together for the code generator.

**Comment by salzhrani** [comment]
This is possibly fixed with #119

**Comment by salzhrani** [comment]
We currently separate our schema in multiple files, which is made very easy by GraphQL code gen. we have our schemas and resolvers in the back end repo and query documents in the front end repo. When the schema changes GraphQL code gen is run to generate resolvers and the introspection plugin to generate the schema.graphqls. which is used by GraphQL-let.
It seems to be somewhat better there was no need for the introspection plugin by having the GraphQL-let read the multiple schemas and generate schema.graphqls by default.

**Comment by marklawlor** [comment]
I think for most users, they are going to expect `.graphql-let.yaml` file to be somewhat similar to graphql-codegen's `codegen.yaml`. Most users who pick up graphql-let are most likely previously used graphql-codegen, so having to rewrite their configs is a frustrating experience.

Also codegen-graphql has already put a lot of thought into their configuration and it seems handle most common scenarios, so why not just use that knowledge?

For example, #124 [graphql-codegen handles this quite well](https://graphql-code-generator.com/docs/getting-started/schema-field) but i'm not sure how `.graphql-let.yaml` plans to handle this

**Comment by piglovesyou** [comment]
Gentlemen, I really appreciate sharing your insights. 

@salzhrani It makes sense. Your workflow reminds me [apollo command](https://github.com/apollographql/apollo-tooling#apollo-servicedownload-output) which generates `./schema.json` as an introspection result by default. I totally agree it should be easier with graphql-let.

Yes @marklawlor, these are the exact points. One thing clearly different from graphql-codegen is that graphql-let lets users forget outputs of GraphQL documents, which leads `.graphql-let.yml` to move away from the spec of `codegen.yml`. I'll choose a simpler config by disabling some features in `codegen.yml` for now but will see the community response. Besides, I also pay attention to [the issue you raised](https://github.com/piglovesyou/graphql-let/issues/96), the final graphql-let.yml should be shaped in an explicit and consistent way.

---

So this is an example of the current picture of the spec. It's almost `schemaOutput` by @marklawlor. (`schemaOutput` is just an intermediate bundle to import, instead of the graphql-codegen result, so I thought perhaps it's better`schemaEntrypoint` or something?)

**.graphql-let.yml**

```yml
# Allow multiple schema files
schema:
    - 'src/schema/**/*.graphqls'
    - '!src/schema/schema.graphqls'

# `schemaEntrypoint`: Generates bound GraphQL schema, from which users will import:
#   - typeDefs for GraphQL server
#   - schema types for resolver implementation
# Required if:
#   - `schema` contains a glob expression
#   - `schemaPlugins` is specified
# Warn if:
#   - The extension is different from `schema`
schemaEntrypoint: src/schema/schema.graphqls

# Generates ${schemaEntrypoint}.d.ts
schemaPlugins:
    - typescript
    - typescript-resolvers

documents: '**/*.graphql'

# Identical to `plugins`. `plugins` will be deprecated, but will work in long term
documentPlugins:  
    - typescript
    - typescript-operations
    - typescript-react-apollo

# Shared config for both `schemaPlugins` and `documentPlugins`
config:
    reactApolloVersion: 3
```

**.gitignore**

```
**/*.graphql.d.ts
src/schema/schema.graphqls         # Generated if `schemaOutput` is specified
src/schema/schema.graphqls.d.ts    # Generated if `schemaPlugins` is specified
```

**What graphql-let disables in `codegen.yml`** (No change. For my study):

* `generates`. Basically graphql-let controls what to generate, except `schemaEntrypoint`.
* Per-output plugins. Users can specify `schemaPlugins` and `documentPlugins`.
* Per-output / Per-plugin config. `config` is always shared to both `schemaPlugins` and `documentPlugins`.

How does it sound?
