### ISSUE TITLE
Get schema definition by introspecting a graphql API

### ISSUE THREAD

**Issue by pranaypratyush** [piglovesyou/graphql-let#99]
I had been using graphql code-gen with the following `codegen.yml`
```
generates:
  ./vendure-types.ts:
    schema: https://demo.vendure.io/shop-api
    documents: 'src/components/ShoppingCart/ShoppingCart.vendure.ts'
    pluckConfig:
      modules:
        - name: apollo-boost
          identifier: gql
    plugins:
      - add: '// tslint:disable'
      - typescript
      - typescript-operations
```
Is this supported?
